### ISSUE TITLE
Setting a limit on revisions don't clean them up

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.revisionmanager#14]
I have a site that uses Dexterity-based content types; I have a limit of 30 revisions that is not being respected so I want collective.revisionmanager (v0.7) to remove all versions above that value:

![selection_023](https://user-images.githubusercontent.com/341393/29371441-bd9d11c2-827e-11e7-828d-bc29f2ae0d3d.png)

![selection_024](https://user-images.githubusercontent.com/341393/29371537-001790d6-827f-11e7-806e-22125533e1f7.png)

Nothing happens after selecting the value and trying to process the excess of revisions.

Clearing the whole history, on the other side, works.

I think this may be a problem with Dexterity and CMFEditions.

**Comment by hvelarde** [comment]
@datakurre FYI

**Comment by tschorr** [comment]
The problem is missing information in the display. The maximum number of revisions to keep is an attribute of `portal_purgepolicy`, the tool responsible for purging revisions older than that. Purging meaning it's doing 'something' with the old object versions, but not deleting the history entries - they are just marked 'purged' (s. https://github.com/plone/Products.CMFEditions/blob/d113fd496121623919e0dfd8db832e8d09ffd42a/Products/CMFEditions/KeepLastNVersionsTool.py#L81).

But `collective.revisionmanager` counts all revisions of an object, also the purged ones. So the number currently displayed includes the purged versions. This is not obvious from the display. 

So this is indeed a problem of `c.revisionmanager` and not Dexterity and/or CMFEditions.

I will add information about the number of purged versions.

**Comment by tschorr** [comment]
btw @hvelarde you should see that the increase in history size is not in proportion to the increase in version numbers as an indication that old revisions are actually purged.

**Comment by tschorr** [comment]
@hvelarde do you want to update the translations before having a release?
